### ISSUE TITLE
cannot inherit the class in linter class

### ISSUE THREAD

**Issue by flavono123** [shortdudey123/yamllint#33]
I'd like to add my custom checker(detector),  parse the yaml nodes recursivley, like`YamlLint::Linter::KeyOverlapDetector`. So I define the abstract class `YamlLint::Linter:RecursiveChecker` then inherits it to `YamlLint::Linter::KeyOverlapDetector`:
```ruby
    class RecursiveChecker
      def parse(psych_parse_data)
        data_start = psych_parse_data.handler.root.children[0]
        parse_recurse(data_start)
      end

      def parse_recurse
        raise NotImplementedError
      end
    end

    ###
    # Detects duplicate keys in Psych parsed data
    #
    class KeyOverlapDetector < RecursiveChecker
    ...
```
But my test codes, just do `YamlLint::Linter#check`, throw an error for the inheritance.

```sh
Traceback (most recent call last):
	4: from test.rb:6:in `<main>'
	3: from test.rb:6:in `require_relative'
	2: from <my-local-path>/yamllint/lib/yamllint/linter.rb:6:in `<top (required)>'
	1: from <my-local-path>/yamllint/lib/yamllint/linter.rb:10:in `<module:YamlLint>'
 <my-local-path>/yamllint/lib/yamllint/linter.rb:132:in `<class:Linter>': superclass mismatch for class KeyOverlapDetector (TypeError)
```

I cannot understand why the inheritance does not work since the following codes has no errors:
```ruby
module Mod
  class A
    class B ;end
    class C < B ;end
  end
end
```

**Comment by flavono123** [comment]
How possible it has the const, `KeyOverlapDetector` , already?!:
```ruby
[8, 17] in <my-local-path>yamllint/lib/yamllint/linter.rb
    8:   # Runs the actual linting
    9:   #
   10:   class Linter
   11:     require 'byebug'
   12:     byebug
=> 13:     attr_reader :disable_extension_check
   14:     attr_reader :errors
   15:     attr_reader :extensions
   16:     attr_reader :valid_extensions
   17:
(byebug) KeyOverlapDetector
YamlLint::Linter::KeyOverlapDetector
(byebug) YamlLint::Linter.constants
[:KeyOverlapDetector]
```

**Comment by flavono123** [comment]
Sorry for my mistakes, I loaded `YamlLint::Linter::KeyOverlapDetector` twice, one from library(`~/.rbenv/shims/) and the other from my own codes:
```ruby
require 'yamllint'

require_relative '<my-local-path>yamllint/lib/yamllint/linter'
...
```

And thanks to be my [debugging teddy bear](http://story.fund/post/114720918282/debugging-teddy-bear) 🐻
